name: Publish NPM module to Nexus
description: Publish NPM module to custom Nexus Server
inputs:
  nexus-user:
    description: Nexus User Name
    required: true
  nexus-password:
    description: Nexus Password
    required: true
runs:
  using: node12
  main: index.js
