name: Publish NPM module to Nexus
description: Publish NPM module to custom Nexus Server
inputs:
  nexus-user:
    description: Nexus User Name
    required: true
  nexus-password:
    description: Nexus Password
    required: true
  nexus-registry:
    description: Nexus registry to pull from
    default: https://nexus.nee.com/repository/npm-group
  nexus-publish-registry:
    description: Nexus registry to publish to
    default: https://nexus.nee.com/repository/npm-innersource/
  nexus-publish-scope:
    description: Publish Scope
    default: "@nextera"
  email:
    description: Developer email
    default: eugene.ryzhikov@nee.com
runs:
  using: node12
  main: index.js
